language: node_js
node_js:
  - "8"
  - "6"
  - "5"
branches:
  only:
    - master
before_script:
  - node node_modules/typescript/bin/tsc -p tsconfig.json
after_success:
  - npm run coveralls